### ISSUE TITLE
Todo before release

### ISSUE THREAD

**Issue by LegoStormtroopr** [LegoStormtroopr/django-themes#1]
* [ ] Display images/media instead of trying to have them as editable text
* [ ] Figure out how to provide links to static files in themes
* [x] Whitelist/blacklist certain paths
